# Generated by Django 5.0.7 on 2024-08-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queryraiserapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
    ]
