# Generated by Django 5.0.7 on 2024-08-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryraiserapp', '0002_rename_departments_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
    ]
