# Generated by Django 5.0.7 on 2024-08-19 15:58

import django.contrib.auth.models
import django.db.models.deletion
import queryraiserapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryraiserapp', '0003_technicianfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('technician', 'Technician'), ('faculty', 'Faculty'), ('admin', 'Admin')], max_length=10),
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('technician_name', models.CharField(max_length=100)),
                ('technician_number', queryraiserapp.models.PhoneNumberField(max_length=10, region='IN', unique=True)),
                ('technician_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryraiserapp.technicianfield')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('queryraiserapp.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
