# Generated by Django 5.0.7 on 2024-09-05 11:32

import queryraiserapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queryraiserapp', '0005_failedloginattempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_phonenumber',
            field=queryraiserapp.models.PhoneNumberField(max_length=10, null=True, region='IN'),
        ),
    ]
