# Generated by Django 5.0.7 on 2024-09-05 13:48

import queryraiserapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queryraiserapp', '0006_faculty_faculty_phonenumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technician',
            options={},
        ),
        migrations.AlterField(
            model_name='technician',
            name='technician_number',
            field=queryraiserapp.models.PhoneNumberField(max_length=10, region='IN'),
        ),
        migrations.AlterUniqueTogether(
            name='technician',
            unique_together={('technician_number', 'technician_field')},
        ),
    ]
