# Generated by Django 5.0.7 on 2024-09-09 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryraiserapp', '0007_alter_technician_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('pending_review', 'Pending Review'), ('closed', 'Closed')], default='new', max_length=20)),
                ('technician_comments', models.TextField(blank=True, null=True)),
                ('faculty_feedback', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryraiserapp.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryraiserapp.faculty')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='queryraiserapp.technician')),
            ],
        ),
    ]
