# Generated by Django 5.0.7 on 2024-09-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryraiserapp', '0008_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='faculty_feedback_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='technician_resolve_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='faculty_feedback',
            field=models.CharField(blank=True, choices=[('resolved', 'Resolved'), ('pending', 'Pending')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('pending_review', 'Pending Review'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='new', max_length=20),
        ),
    ]
