# Generated by Django 5.1 on 2024-09-12 14:21

import queryraiserapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queryraiserapp', '0009_complaint_faculty_feedback_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='technician_number',
            field=queryraiserapp.models.PhoneNumberField(max_length=13, region='IN'),
        ),
    ]
