# Generated by Django 5.1 on 2024-09-12 14:26

import queryraiserapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queryraiserapp', '0010_alter_technician_technician_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_phonenumber',
            field=queryraiserapp.models.PhoneNumberField(max_length=13, null=True, region='IN'),
        ),
    ]
