# Generated by Django 5.1 on 2024-09-13 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryraiserapp', '0011_alter_faculty_faculty_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='faculty_feedback',
            new_name='faculty_status',
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='closed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='faculty_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reopen_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='technician_status',
            field=models.CharField(blank=True, choices=[('resolved', 'Resolved'), ('pending', 'Pending')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
