# Generated by Django 5.1 on 2024-09-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryraiserapp', '0012_rename_faculty_feedback_complaint_faculty_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('pending_review', 'Pending Review'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='new', max_length=20),
        ),
    ]
