# Generated by Django 5.1 on 2024-09-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryraiserapp', '0013_alter_complaint_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='faculty_comments',
            new_name='faculty_pending_comments',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='technician_comments',
            new_name='faculty_resolved_comments',
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reopen_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='technician_pending_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='technician_resolved_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
