# Generated by Django 5.1 on 2024-09-21 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryraiserapp', '0014_rename_faculty_comments_complaint_faculty_pending_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='faculty_pending_comments',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='faculty_resolved_comments',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='reopen_reason',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='technician_pending_comments',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='technician_resolved_comments',
        ),
        migrations.AddField(
            model_name='complaint',
            name='faculty_comments',
            field=models.TextField(blank=True, help_text='Comments from the faculty (both pending and resolved)', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='technician_comments',
            field=models.TextField(blank=True, help_text='Comments from the technician (both pending and resolved)', null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='faculty_status',
            field=models.CharField(blank=True, choices=[('resolved', 'Resolved'), ('pending', 'Pending')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('pending_review', 'Pending Review'), ('pending', 'Pending'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='technician_status',
            field=models.CharField(blank=True, choices=[('resolved', 'Resolved'), ('pending', 'Pending')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ReopenHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('reopen_time', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reopen_history', to='queryraiserapp.complaint')),
            ],
        ),
    ]
