# Generated by Django 5.1 on 2024-09-25 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryraiserapp', '0015_remove_complaint_faculty_pending_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='queryraiserapp.faculty'),
        ),
    ]
